config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources 'users', only: [:index, :show]
  resources :questions do
    resources :answers do
      resources :answer_votes, only: [] do
        collection do
          post :plus
          post :minus
        end
      end
    end
    resources :question_votes, only: [] do
      collection do
        post :plus
        post :minus
      end
    end
  end
  resources 'tags'
  resources :bookmarks, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
  has_many :tags, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :question_votes, dependent: :destroy
  has_many :question_vote_users, through: :question_votes, source: :user
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :bookmarks, dependent: :destroy

  acts_as_taggable
  scope :index_all, -> {
  select(:id, :title, :content, :created_at, :user_id, :updated_at, :vote_count, :bookmarks_count)
  .includes(:user)
  }
  paginates_per 4
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_question_tags_to_gon, only: [:index, :show, :edit]
  before_action :set_available_tags_to_gon, only: [:index, :show, :new, :edit]
  helper_method :sort_column, :sort_direction

  def index
    @questions = Question.index_all.page(params[:page]).order(sort_column + ' ' + sort_direction).includes(:tags)
    gon.question_tags = @questions.map { |q| q.tag_list }
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    authenticate_user!
    if params[:back]
      @question = Question.new(questions_params)
      @question_tag_list = ActsAsTaggableOn::Tag.all.pluck(:name)
    else
      @question = Question.new
      gon.question_tags = ActsAsTaggableOn::Tag.all.pluck(:name)
    end
  end

  def create
    @question = Question.new(questions_params)
    @question.user_id = current_user.id
    @question.tag_list = params[:tags]
    if @question.save
      redirect_to questions_path, notice:"投稿されました"
    else
      @question = Question.new(questions_params)
    end
  end

  def edit
  end

  def update
    @question.update(questions_params)
    redirect_to questions_path, notice:"投稿を更新しました"
  end

  def destroy
    @question.destroy
    redirect_to root_path, alert:"投稿を削除しました"
  end

  def show
    authenticate_user!
    @answer = @question.answers.build
    @answers = @question.answers
  end

  private
    def questions_params
      params.require(:question).permit(:title, :content, :tag_list)
    end
    def set_question
      @question = Question.find(params[:id])
    end

    def sort_column
      Question.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def set_question_tags_to_gon
    #  gon.question_tags = @question.tag_list
    end

    def set_available_tags_to_gon
      gon.available_tags = Question.tags_on(:tags).pluck(:name)
    end
end

app/views/questions/_bookmark.html.erb
<div class="container">
  <table class="bookmarkedquestion">
    <tr>
      <th>投票された数</th>
      <th>質問のタイトル（クリックするとリンク先に飛べます）</th>
      <th>作成日</th>
    </tr>
    <% @user.bookmarks.each do |bookmark| %>
    <tr>
      <td class="bookmarkedquestion-td"><%= bookmark.question.vote_count %>票</td>
      <td class="bookmarkedquestion-td"><%= link_to question_path(bookmark.question) do %><%= bookmark.question.title %><% end %></td>
      <td class="bookmarkedquestion-td"><%= bookmark.question.created_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <%= f.label :タイトル %>
  <%= f.text_field :title, class: "edit-title", placeholder:"プログラミングに関しての質問は何ですか？具体的に書いてください。",required:true%>
  <%= f.text_area :content, class: "editor",required:true %>

  <%= f.label :tag_list, "タグ" %>
   <ul class="tag_form">
     <div id="question-tags" class="tagit ui-widget ui-widget-content ui-corner-all border-none">
     </div>
   </ul>
  <%= f.submit '投稿する',class:"submit-button"%>
<% end %>

<script>
   (function(){
     if (gon.question_tags != null) {
       var tags = gon.question_tags
       $('#question-tags').tagit({
         availableTags: tags
       });
     }
   });
 </script>

app/views/questions/edit.html.erb
<div class="content">
  <main class="edit-main">
    <%= render 'form' %>
  </main>
  <div id="editSideber"class="edit-sidebar">
    <p>質問するその前に</p>
    <p><b>質問するその前に</b></p>
    <p>このサイトはプログラミングに関するQ&Aを対象にしています。</p>
    <p>単なる議論に終わらず、解決可能な質問を歓迎します。</p>
    <p>これまでに試したことや調べたことを含め、質問内容を詳しく書くことで回答がつきやすくなります。</p>
    <p>使い方がわからないなど、このサイトそのものについての質問でしたら、<a href="#">meta</a>で受け付けています。</p>
    <a href="#">ヘルプセンターへ »</a>
    <a href="#">質問の手引き »</a>
  </div>
</div>

app/views/questions/index.html.erb
<div class="content">
  <main>
    <div class="__head">
      <h2>すべての質問</h2>
      <ul>
        <li class="current_tab"><%= sortable "created_at", "新着" %></li>
        <li><%= sortable "vote_count", "票" %></li>
        <li><%= sortable "bookmarks_count", "お気に入りランク" %></li>
      </ul>
    </div>
    <div class="q-wrap">
      <ul class="q-list">
      <% @questions.each do |question| %>
        <li class="q-item">
          <div class="count-wrap">
            <div class="votes box">
              <p><%= question.vote_count %><sapn class="num-text">票</sapn></p>
            </div>
            <div class="status box">
              <p><%= question.answers.count %><span class="num-text">回答</span></p>
            </div>
            <div class="views box">
              <p><span class="read-count">1230件の閲覧数</span></p>
              <p><span class="bookmarks_count"><%= question.bookmarks_count %> 件のお気に入り</span>
            </div>
          </div>
          <div class="summary">
            <h3>
              <%= link_to question.title, question_path(question),method:"get", class:"q-title" %>
            </h3>
            <p class="q-text"><%= question.content %>...</p>
            <p class="tags"><%= question.tag_list %></p>
            <div class="user-block">
              <div class="log"><p><a>質問日時: </a>14年12月19日 8:02</p></div>
              <div class="user">
                <div class="user-avatar"><%= profile_img(question.user) %></div>
                <div class="user-name-box">
                  <%= link_to question.user.name, user_path(question.user),class: "user-name" %>
                  <p class="user-info">
                    <span class="reputation-score" title="信用度スコア: ">信用度：<%= question.user.reputation_count %></span>
                  </p>
                </div>
              </div>
            </div><!-- user-block -->
          </div>
        </li>
      <% end %>
      </ul>
      <%= paginate @questions %>
    </div>
  </main>


  <div id="sidebar">
    <button class="question-buttton">
      <%= link_to "質問する", new_question_path, method: :get %>
    </button>
    <div class="question-status box" id="question-status box">
      <h4 class="title"><%= Question.count %></h4>
      <p>件の質問</p>
    </div>

    <div class="module" id="recent-tags">
      <h4 class="recent-tags-title">最近のタグ</h4>
      <ul id="recent-tags-list">
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">javascript</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">67</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">python</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">52</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">java</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">48</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">linux</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">40</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">css</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">27</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">html</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">25</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">ruby on rails</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">19</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">git</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">16</span>
        </li>
        <li class="recent-tags-item">
          <a href="#" class="tag post-tag" rel="tag">swift3</a>
          <span class="item-multiplier-x">×</span>
          <span class="item-multiplier-count">12</span>
        </li>
      </ul>
      <p class="tags-all more-tags-all"><a href="#">関連するタグを更に表示</a></p>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="content">
  <main class="edit-main">
    <%= render 'form' %>
  </main>
  <div id="editSideber"class="edit-sidebar">
    <p>質問するその前に</p>
    <p><b>質問するその前に</b></p>
    <p>このサイトはプログラミングに関するQ&Aを対象にしています。</p>
    <p>単なる議論に終わらず、解決可能な質問を歓迎します。</p>
    <p>これまでに試したことや調べたことを含め、質問内容を詳しく書くことで回答がつきやすくなります。</p>
    <p>使い方がわからないなど、このサイトそのものについての質問でしたら、<a href="#">meta</a>で受け付けています。</p>
    <a href="#">ヘルプセンターへ »</a>
    <a href="#">質問の手引き »</a>
  </div>
</div>

app/views/questions/show.html.erb
<div class="__head question-show__head">
  <h2><%= @question.title %></h2>
</div>
<div class="content">
  <main>
    <div class="q-list">
      <div class="q-block">
        <div class="evaluation">
          <% if @question.user.id == current_user.id %>
            <a class="evaluation-good" onClick="window.alert('自分の質問には投票できません');"></a>
          <% else %>
            <%= link_to "", plus_question_question_votes_path(question_id: @question.id), method: :post, class: 'evaluation-good' %>
          <% end %>
          <p id="evaluation-count"><%= @question.vote_count %></p>
          <% if @question.user == current_user %>
            <a class="evaluation-bad" onClick="window.alert('自分の質問には投票できません');"></a>
          <% else %>
            <%= link_to "", minus_question_question_votes_path(question_id: @question.id), method: :post, class: 'evaluation-bad' %>
          <% end %>
        </div>
        <div class="summary">
          <p class="q-text-show"><%= @question.content %></p>
          <!-- tag表示　-->
           <%= include_gon %>
           <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
           <!-- tag表示　-->
          <div class="q-show-link-box">
            <a href="#">共有</a><a href="#">この回答を改善する</a>
          </div>
          <div id="bookmark-clip">
            <p><%= render 'bookmarks/bookmark', locals: { bookmark: @bookmark, question: @question } %></p>
          </div>
          <div class="user-block q-show-bg">
            <div class="log"><p>質問日時:30分前</p></div>
            <div class="user q-show">
              <div class="user-avatar"><%= profile_img(@question.user) %></div>
              <div class="user-name-box">
                <%= link_to @question.user.name, user_path(@question.user.id), class:"user-name" %>
                <p class="user-info">
                  <span class="reputation-score" title="信用度スコア: ">信用度：<%= @question.user.reputation_count %></span>
                </p>
              </div>
            </div>
          </div><!-- user-block -->
          <% if current_user.id == @question.user.id %>
            <%= link_to "編集", edit_question_path(@question.id), class:"q-title" %>
            <span> ｜ </span>
            <%= link_to '削除', question_path(@question.id), class:"q-title" , method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          <% end %>
          <div class="q-show-add-comment">
            <a href="#">コメント追加</a>
          </div>
        </div>
      </div>
    </div>
    <div class="__head question-answer-head">
      <h2><%= @question.answers.count %> 件の回答</h2>
      <ul>
        <li><a href="#">アクティブ</a></li>
        <li><a href="#">古い順</a></li>
        <li class="current_tab"><a href="#">票</a></li>
      </ul>
    </div>
    <ul id="answers_area" class="q-list">
      <%= render partial: 'answers/index', locals: { answers: @answers, question: @question } %>
    </ul>
    <div class="answer">
      <h2>回答</h2>
      <%= render partial: 'answers/form', locals: { answer: @answer, question: @question } %>
      <p>質問を投稿することで<a href="#">プライバシー ポリシー</a>および<a href="#">サービス利用規約</a>に同意したものとみなされます。</p>
      <p>求めていた回答ではありませんか?<a href="#" class="tag">php</a>のタグが付いた他の質問を参照するか、自分で質問をする。</p>
  </main>

  <div id="sidebar">
    <div class="question-show__status box">
      <P><span>質問を投稿</span><span class="number" >2</span> 日前</P>
      <P><span>閲覧回数</span><span class="number" >38</span> 回</P>
      <P><span>アクティブ</span><span class="number" >2</span> 日前</P>
    </div>
    <div class="module">
      <h3 class="relative-q-title">関連する質問</h3>
      <ul id="relative-q-list">
        <li><a class="propatytag">1</a><a href="#" class="q-link">phpでexecを用いてpsqlを動かす際にパスワードを与える方法について</a></li>
        <li><a class="propatytag propatytag--active">1</a><a href="#" class="q-link">PHPMyAdminはどうやってSQLをダンプしているのか</a></li>
        <li><a class="propatytag propatytag--active">9</a><a href="#" class="q-link">72文字を超えるパスワードを許容したい場合、password_hashを使うべきではない？</a></li>
        <li><a class="propatytag">1</a><a href="#" class="q-link">PHPからMySQLに接続がうまくできない</a></li>
        <li><a class="propatytag">2</a><a href="#" class="q-link">phpmyadminのインストールができない</a></li>
        <li><a class="propatytag">2</a><a href="#" class="q-link">phpmyadminが表示されない</a></li>
        <li><a class="propatytag propatytag--active">0</a><a href="#" class="q-link">nginx+php-fpm+phpmyadminセットアップ　phpファイルが動かない</a></li>
        <li><a class="propatytag">0</a><a href="#" class="q-link">phpMyAdminのポートフォワードがうまくいかない</a></li>
        <li><a class="propatytag">0</a><a href="#" class="q-link">phpからmysqlへの接続</a></li>
        <li><a class="propatytag">0</a><a href="#" class="q-link">PHPでパスワード認証がある外部サイトに自動でログインしたい</a></li>
      </ul>
    </div>
  </div>
</div>