config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources 'users', only: [:index, :show]
  resources :questions do
    resources :answers do
      resources :answer_votes, only: [] do
        collection do
          post :plus
          post :minus
        end
      end
    end
    resources :question_votes, only: [] do
      collection do
        post :plus
        post :minus
      end
    end
  end
  resources 'tags'
  resources :bookmarks, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :content, presence: true
  has_many :answer_votes, dependent: :destroy
  has_many :answer_vote_users, through: :answer_votes, source: :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = current_user.answers.build(answer_params)
    @question = @answer.question
    respond_to do |format|
      if @answer.save
        format.js { render :index }
      else
        format.js { render :new }
      end
    end
  end
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    render :index
  end
  private
    def answer_params
      params.require(:answer).permit(:question_id, :content)
    end
end

app/views/answers/_form.html.erb
<%= form_for([question, answer], remote: true) do |f| %>
  <%= f.hidden_field :question_id %>
  <%= f.text_area :content, class:"editor",  required:true  %>
  <div class="editor-preview"><p style="text-align:center">preview入る予定</p></div>
  </div>
  <% if @question.user == current_user %>
    <%= f.submit id:"myQuestion",class:"submit-button",value:"回答を投稿" %>
  <% elsif user_signed_in? %>
    <%= f.submit class:"submit-button",value:"回答を投稿" %>
  <% else %>
    <%= f.submit id:"notLogin",class:"submit-button",value:"回答を投稿" %>
  <% end %>
<% end %>

app/views/answers/_index.html.erb
<% answers.order("created_at").each do |answer| %>
  <% unless answer.id.nil? %>
    <li class="q-item">
      <div class="evaluation">
        <% if answer.user.id == current_user.id %>
          <a class="evaluation-good" onClick="window.alert('自分の回答には投票できません');"></a>
        <% else %>
          <%= link_to "", plus_question_answer_answer_votes_path(question_id: answer.question_id, answer_id: answer.id), method: :post, class: 'evaluation-good' %>
        <% end %>
        <p id="evaluation-count"><%= answer.vote_count %></p>
        <% if answer.user.id == current_user.id %>
          <a class="evaluation-bad" onClick="window.alert('自分の回答には投票できません');"></a>
        <% else %>
          <%= link_to "", minus_question_answer_answer_votes_path(question_id: answer.question_id, answer_id: answer.id), method: :post, class: 'evaluation-bad' %>
        <% end %>
      </div>
      <div class="summary">
        <p class="q-text-show"><%= answer.content %></p>
        <div class="q-show-link-box">
          <a href="#">共有</a><a href="#">この質問を改善する</a>
        </div>
        <div class="user-block">
          <div class="log"><p>回答日時:30分前</p></div>
          <div class="user">
            <div class="user-name-box">
              <%= link_to answer.user.name, user_path(answer.user.id), class:"user-name" %>
              <p class="user-info">
                <span class="reputation-score" title="信用度スコア: "><%= answer.user.reputation_count %></span>
                <span class="badge" title="5 個の銅バッジ">
                  <span class="badge-icon badge3"></span>
                  <span class="badgecount">5</span>
                </span>
              </p>
            </div>
          </div>
          <% if current_user.id == answer.user.id %>
            <p class="delete">
              <%= link_to '削除', question_answer_path(question, answer), method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
            </p>
          <% end %>
        </div><!-- user-block -->
      </div>
    </li>

  <% end %>
<% end %>

app/views/answers/index.js.erb
$("#answers_area").html("<%= j(render 'answers/index', { answers: @answer.question.answers, question: @answer.question }) %>");
$('.editor').val('');